logging:
  level:
     zipkin: DEBUG
     io:
        pivotal: DEBUG
     com:
        netflix: DEBUG
     org:
        springframework:
           web: DEBUG
           cloud: 
             sleuth:
               log: WARN
