spring:
  application:
     name: quotes-service
pivotal:
  quotes:
#    quote_url: https://api.iextrading.com/1.0/stock/{symbol}/quote
#    quotes_url: https://api.iextrading.com/1.0/stock/market/batch?symbols={symbols}&types=quote

    use_cache: false
    quote_url: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}
    quotes_url: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}

    quotes_url2: http://globalquotes.xignite.com/v3/xGlobalQuotes.json/GetGlobalDelayedQuote?IdentifierType=Symbol&Identifier={symbol}&_token=5C00193922334CF2BE564F76D2E233CF
    companies_url: http://dev.markitondemand.com/Api/v2/Lookup/json?input={name}
    yahoo_rest_query: https://query.yahooapis.com/v1/public/yql?q=use "{env}" as quotes;select * from quotes where symbol in ('{symbol}')&format={fmt}
    yahoo_env: https://raw.githubusercontent.com/yql/yql-tables/master/yahoo/finance/yahoo.finance.quotes.xml
security:
  basic:
    enabled: false
